---
title: "运营日记"
---

::: callout-note
## 2024年9月11日

合抱之木，生于毫末；九层之台，起于累土；千里之行，始于足下。

面对这100万字的文稿，四本书，受够了复制粘贴的苦，要是整理成“完美的”pdf，要到猴年马月。

我要先上线，再追求所谓的“完美”。

目前我尚未解决的事情非常多，比如网站在墙外，墙内用户可能需要梯子……比如我没有什么收钱的方式，只能先通过微信收钱……比如LaTeX引用代码的时候，格式总是乱掉，搞得我有点崩……

9年前，我录电台时，只有一个Nexus手机，不也开始了么？我相信我做的事情对用户是有“价值”的。
:::

::: callout-note
## 2024年9月12日

社区运行了一天，碰到了好多我想到的，和我没想到的问题。

想到的：网络，梯子，这个问题实在是太大了。

没想到的：用户的注册邮箱如果是hotmail与outlook，那么注册邮件会被归类到垃圾邮件中。
:::

::: callout-note
## 2024年9月14日

就跟我工作时候一样，不想升级网站。我怕升级挂了，自己debug，自己难受。属实是没苦硬吃。

由于我用的是开源的discourse搭建的社区，这个社区有手机端，我就推广了一下。
:::

::: callout-note
## 2024年9月15日

我还是提心吊胆的升级了网站，在升级之前，我仔细研究了升级的原理，做了备份。其实，我对puma这个东西不太了解，其它的我还是挺了解的，不知道为什么每次启动puma，就像卡死了一样。以前我用passenger，就比较快。

我要花点时间研究一下puma的工作机制。
:::

::: callout-note
## 2024年9月17日

今天把Java书的前10章复制粘贴完毕。由于我使用LaTeX来排版的，还是遇到了好多毛病。比如有些汉字不支持，比如“喆”这个字。

还有一些格式的问题，不过，我想先搞定文字的“复制粘贴”，再搞其它的。

今天中秋节，回老家了。回来后，终于把前10章搞完了。已经上传到社区上了。
:::

::: callout-note
## 2024年9月18日

把书里的补充材料，主要是论文和一些代码，本想打包上传到社区，发现社区实在是上传不了这么大的文件。就压缩了一个包，上传到微软的云盘里。

复制粘贴到第15章了，已经有300页了，我想把字调小一点。不想超过400页。
:::

::: callout-note
## 2024年9月23日

我已经把第一本书都复制粘贴完了。又对LaTeX进行了一些美化，希望快点把书整的非常漂亮。本来不想超过400页，结果还是快500页了。

:::

::: callout-note
## 2024年9月24日

我花了一下午的时间，试图让生成pdf时，自动加上封面，没成功。

各种错误，不运行，烦死了。最后决定还是手动加吧，用Adobe Acrobat加。

我就是自动化一点，竟然这么难搞，烦啊。

:::


::: callout-note
## 2024年10月1日

挑了一个好日子，至少非常容易记的日子——国庆节——发了一篇公众号和电台。宣布了我要做个小买卖。

编程书搞好了，但是App还没完工，有点遗憾。

我的目标是写几本“最好的”Java编程书。再做一个优秀的软件。
:::

::: callout-note
## 2024年10月4日

我的电子书被人购买后，直接分享到网上了。怎么说呢，有点不爽，但是又觉得电子书，总归会被上传到网上的。

我不能有受害者心理，不能跟人性对抗。做有用的事。

:::

::: callout-note
## 2024年10月6日

这两天，我在B站直播讲我的书，直播结束后，我再从B站上下载我的内容，上传到YouTube上。今天，B站说录播出问题了。

我研究了下，我应该设置好OBS让它边直播边录的。太相信B战的技术了，让我返工了第4期。

:::

::: callout-note
## 2024年10月14日

这几天我一直在B站上直播，但是观看的人数一直都是非常的少。最多的时候30人吧，所以，我有时候会进入一种焦虑的状态。

我其实也没什么好办法化解我的情绪。xueban.app这个网站有点慢，我买了一个好机器，有11G内存呢，想转移一下网站。我要细心的规划一下，希望别给整坏了。

:::

::: callout-note
## 2024年10月17日

今天开始，我研究了一下如何将xueban.app这个社区平滑的移动到有11G内存的VPS上。我有两三个方案，但是哪个方案都不够“平滑”，我还是仔细研究清楚再动手吧，不想搞挂了。

:::