::: callout-tip
## 姑且就叫“极简创业”吧！


我从来没有轰轰烈烈的创过业，像网上那样有一个创意、然后融资、招人……开发产品……改变世界……

我也不知道我自己卖自己写的文档算不是创业，应该算吧，毕竟摆摊也算创业呢（前总理不是搞地摊经济么？），我想记录一下我的感想。供人参考。

虽然我跟摆地摊没法比，感觉比地摊还要“简朴”，还要“简陋”，叫“地摊创业”也不合适，姑且称之为“**<u>极简创业</u>**”吧。

::: {.right-align}
--- 2024年9月18日23:08
:::
:::


::: callout-tip
## 我婚姻失败的原因

在群里，不知道怎么谈起结婚这个话题，我的婚姻是以失败告终的。前妻被我捉奸，然后比较“和平”的离婚。

受伤是有的，在我婚姻失败后，我才搞清楚一件事情，“我爱的人”，“爱我的人”与“接受我的爱的人”，这三种人有本质的区别，很难是同一个人。

我是找了“我爱的人”，然后拼命追，而前妻仅仅是“接受我的爱的人”，并不等于爱我。所以，她做事从来不考虑我，而只是接受我的爱。所以她始终没变心，她出轨只是又接受了另一个人的爱。

虽然惨痛，但是，这样想来，我没失去什么宝贵的东西（一个不爱我的人，没什么珍惜的），她也没失去什么（一个她不爱的人，也没什么珍惜的）。

如果花了很大的力气才追上，不如花了很大的力气追不上。

当然，我不会再结婚了，我识人能力不行，行动力又太行，追的啥人都没看清楚，就开始追了，也是报应吧。

::: {.right-align}
--- 2024年9月19日22:05
:::
:::

::: callout-tip
## 别人为什么要付钱呢？

付钱，是想解决一个问题，是把一个问题卖给了我。而我，需要解决这个问题。

比如，解决编程的问题。

::: {.right-align}
--- 2024年9月21日08:35
:::
:::

::: callout-tip
## 纸上得来终觉浅，推广需要不要脸

我看了两遍Lex Fridman对Pieter Levels的访谈，给我最深的感想是：推广极为重要，要远高于技术。

Pieter所用的技术是PHP和JQuery，这不算先进，但是其开发的速度与推广的技能，太值得我学习。

国运 > 平台 > 金钱 > 面子

他太能推广了，推广到我感觉到有点不好意思，以后我要克服这一点。不要不好意思。

::: {.right-align}
--- 2024年9月23日11:49
:::
:::

::: callout-tip
## 闲来写就青山卖，不使人间造孽钱。

买我产品的，100%都是听我电台的长期听众。我已经录了9年电台了，虽然我录电台的时候，从来也没想到过要写文档，要写软件，本来以为打工就算了。

我要在这个狭窄的领域，继续深耕下去。（除了写作，写软件，我也没有其他的技能）。

::: {.right-align}
--- 2024年10月1日22:04
:::
:::

::: callout-tip
## 尽可能的简洁

跟购买我社区的电台听众聊天，总结如下：

最初，我想出版书，是想“装逼”。后来“装逼”的成本实在太大了，主要是时间成本，出版行业有数十年的惯性，我不可能改变丝毫。

后来，简单一点。我能写作，写作之后分发给读者，并且收到钱，搞定。我不用通过出版社就可以。（有一点点酸葡萄心理，出版社比我强势，我对出版社无能为力，这个我认可 :）

简单的事物失效点比较少，复杂的事物更容易失效。

::: {.right-align}
--- 2024年10月2日23:20
:::
:::

::: callout-tip
## 我写的书马上就出现了“盗版”

有个家伙付了200块，买了pdf，几分钟就把盗版上传到他的群里了。后来有人告诉我了，我去问他，他一副无所谓的样子。

我要做这件事，盗版是没办法解决的。没办法依靠人性来解决问题，有的人性本来就是恶的，有的人性本来就是好的。

事情很难，但是要坚持做下去。

::: {.right-align}
--- 2024年10月5日10:20
:::
:::

::: callout-tip
## 创业焦虑

如何才能把东西卖出去呢？这是我最想知道的问题。打工会有焦虑，创业也有自己的焦虑。

::: {.right-align}
--- 2024年10月14日21:49
:::
:::

::: callout-tip
## 拒绝不合理的要求应该是对的

有人来问我要免费的社区账号，我拒绝了，两个人。虽然他们确实保证不会在社区里捣乱，但是这对已经交了200块的人是不公平的。

如果不付出钱，就不会珍惜这个账号。我希望社区里能够成为一个真正有温度的社区。

::: {.right-align}
--- 2024年10月17日22:29
:::
:::

::: callout-tip
## 保持长期的联系是非常重要的

我做了好多年电台，大概有9年了，我做电台的时候，从来没想过将来会写书。我写书的时候，我也没想过出版社会不想出版。出版社不想出版之后，我是在听众的建议下，开始卖书的。

我没有计划这一切，都是自然而然发生的。是什么原因让听众肯拿200块来购买我的书呢？我觉得是长期的联系，让听众认为我这个人还不错。

做出决定并不是临时起意的，而是听电台，加关注，调查，考虑，最后购买。（如果我买东西的话，我会这样，我会买我认可的人写的东西。）

::: {.right-align}
--- 2024年10月18日14:23
:::
:::

::: callout-tip
## 如何面对批评与谩骂

自从做电台以来，毕竟在网上想发声，一个必须要面对的事情是，如何面对谩骂。就是，完全不用理会，直接不回复就是了。

本来就是小众电台，不必讨好任何人。比如，我的普通话，实在是练不出来，难道要先去练普通话么？

::: {.right-align}
--- 2024年10月26日08:25
:::
:::