---
title: “付款方式”与“学伴”社区
---

# 付款方式

目前我没有好的方式，也没有第三方可以担保，以后我可能会开个淘宝店什么的，或者加个stripe收款，但是目前还没有。

如果我贸然放一个微信收款，很不合理，就跟加了个“美女”，上来第一句话就是今天她过生日，给她发个红包再聊一样荒唐。

我想把这事做成一个长久的“卖买”，总有一少部分人想学习“编程”，而我在“编程”这个领域工作了20年。这个“买卖”的本质是我以“电子书”和社区的方式售卖“知识与服务”。除了获得4本电子书，这200块的门槛足以阻拦白嫖党加入社区，搞的社区乌烟瘴气。

目前，我只服务加过微信的电台听众。

**你发给我红包或者转账以后，[一定要提供一个可用的电子邮件]{.underline}，我会把社区的邀请链接发给您。社区不支持公开注册。**

# “学伴”社区

电子书很容易就复制了，可能我也赚不到什么钱。这200块钱里，有一项服务是不可取代的，我搞了一个社区，叫学伴，这个名字不是山东大学启发我的，网址是<https://xueban.app>。如果你购买了这4本书，我会给你一个社区的邀请链接，这个社区的主要话题是：[**学技术、学外语、搞事业**]{.underline}。

所谓的搞事业，有可能是学生想出国读书了，找个便宜点的国家；也有可能是找个远程工作，但是不知道怎么弄；也有可能是移民到国外，不要再这么卷了；如果你一直打工，到了35岁，HR发个邮件通知你，明天你不用来了，在社区里，咱们谈谈如何尽量避免这种情况…… 我以后会在电台里多邀请一些在国外学习工作生活的人，采访一下他们，给大家，包括我，开开眼界。

::: callout-tip
## 如果没有审核资源，社区一定要有个付费墙

有本书叫《怪诞行为学》，作者在书里讲了一种现象，如果你把布朗尼——一种 巧克力蛋糕——设置为免费，不管需要不需要，人们都会趋之若骛，排起长队。 只要你设置一个价格，哪怕只有1美分，也会让排队的人消失。他把这个现象起了个名字叫布朗尼效应。

在中国，会更严重一点。如果你搞了个免费公开的社区，就会有人来请你喝茶——实际上没有茶，也没有水，更没有布朗尼蛋糕，只有写保证书，并关掉社区这一条路。我试过，可以说是赔了金钱又剪了网线，不能再细讲了。
:::

我卖电子书，也是践行**搞事业**的理念。打工了这么多年，我希望成为一个会做生意的人。目前，我理解的生意人，应该是提供相应的服务，收取相应的报酬。

这4本书，我都会提供前4章的预览，你可以先看看前4章，再决定要不要花这个钱。我给这几本书定了一个上线的日期。

| 书名                        | 目前完成度 | 完整上线日期 | 提供的格式 |
|-----------------------------|------------|--------------|------------|
| 《借助AI学习Java编程》      | 100%       | 2024.9.30前  | pdf        |
| 《借助AI用Java制作2D游戏》  | 100%       | 2024.12.31前 | pdf        |
| 《借助AI用Java制作GUI软件》 | 90%        | 2025.3.31前  | pdf        |
| 《Java Spring》             | 50%        | 2025.9.31前  | pdf        |

::: {.callout-tip icon="false"}
我确实想提供epub的格式，但是…… 代码在epub里实在是太丑了，看不下去 :(
:::

从做电台来看，我还是比较能坚持的，**我想做一个坚持长期主义的生意人。写书，录电台，录中英文编程视频……** 我也要践行**学技术、学英语、搞事业**的理念。

既然结局已定，在死神来敲门之前，好好体验人生吧……[**我想成为做编程教学最好的电台主播**]{.underline}，太虚的大话就不说了，免得像出书一样，被现实狠狠地打脸。

::: {.callout-tip icon="false"}
## 只要加足够的定语，就一定能成为最好的。

“我想成为做编程教学最好的电台主播”，肯定有人不相信，是的，我知道至少有一个人不相信。

那么，我再加几个定语吧：我想成为做Java编程教学最好的山东籍电台男主播…… 只要定语足够多，那么，一定能成为最好的。
:::
